#!/usr/bin/env bash
# Install nginx web server
apt update

apt install -y nginx

echo 'server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    location / {
        return 200 "Hello World!";
    }
}' > /etc/nginx/sites-available/default

service nginx restart
