#!/usr/bin/env bash
# Configuring Nginx server to have a custom 404 page
sudo apt update
sudo apt install nginx
sudo nano /var/www/html/404.html
echo "Hello World!" > /var/www/html/404.html
touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
server {
    # Other server configurations...

    location / {
        # Other location configurations...
        error_page 404 /404.html;
    }

    # Other server configurations...
}
sudo nano /etc/nginx/sites-available/default
sudo systemctl restart nginx
